---

- name: Install apache httpd and required modules
  apt:
    name: apache2
    state: present
  tags:
    - apache

- name: Enable required apache modules
  apache2_module:
    state: present
    name: "{{item}}"
  with_items:
    - rewrite
    - proxy
    - proxy_http
    - ssl
    - status
  notify: restart apache
  tags:
    - apache

- name: Drop the apache2.conf in place and restart Apache
  template:
    src: apache2.conf.j2
    dest: /etc/apache2/apache2.conf
    owner: root
    group: root
    mode: "644"
    backup: yes
  notify: restart apache
  tags:
    - apache
