---

 - name: Install apache httpd and required modules
   apt: name={{ item }} state=present
   with_items:
     - apache2
     - libapache2-mod-evasive
   tags:
     - apache

 - name: Drop the mod-evasive.conf file in place
   template: src=mod-evasive.conf.j2 dest=/etc/apache2/mods-available/mod-evasive.conf
    owner=root group=root mode=644
   tags:
     - apache

 - name: Enable required apache modules
   apache2_module: state=present name={{item}}
   with_items:
     - rewrite
     - proxy
     - proxy_http
     - ssl
     - mod-evasive
   notify: restart apache
   tags:
     - apache

 - name: Drop the apache2.conf in place and restart Apache
   template: src=apache2.conf.j2 dest=/etc/apache2/apache2.conf
    owner=root group=root mode=644
   notify: restart apache
   tags:
     - apache
